@baseUrlDev=http://localhost:3055/v1/api/shop

### Sign-up
POST {{baseUrlDev}}/sign-up
Content-Type: application/json
x-api-key: 9acea3ac6cc47503e813c124d8a5b8a7f6185ea714a8274df81dd0f735dd8cd67bb53c9eee65ecdb2cfa51d3f84c451a043c34f08da0668417717319aa4f1c46

{
    "name": "Shop TipJS",
    "email": "shoptipjs@gmail.com",
    "password": "abc123"
}