@baseUrlDev=http://localhost:3055/v1/api/shop

### Sign-up
POST {{baseUrlDev}}/sign-up
Content-Type: application/json
x-api-key: 9acea3ac6cc47503e813c124d8a5b8a7f6185ea714a8274df81dd0f735dd8cd67bb53c9eee65ecdb2cfa51d3f84c451a043c34f08da0668417717319aa4f1c46

{
    "name": "Shop TipJS",
    "email": "shoptipjs@gmail.com",
    "password": "abc123"
}


### Sign-in
POST {{baseUrlDev}}/sign-in
Content-Type: application/json
x-api-key: 9acea3ac6cc47503e813c124d8a5b8a7f6185ea714a8274df81dd0f735dd8cd67bb53c9eee65ecdb2cfa51d3f84c451a043c34f08da0668417717319aa4f1c46

{
    "email": "shoptipjs@gmail.com",
    "password": "abc123"
}

### Sign-out
POST {{baseUrlDev}}/sign-out
Content-Type: application/json
x-api-key: 9acea3ac6cc47503e813c124d8a5b8a7f6185ea714a8274df81dd0f735dd8cd67bb53c9eee65ecdb2cfa51d3f84c451a043c34f08da0668417717319aa4f1c46
x-client-id: 64ea05bcfe9f4fe2000b610c
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVhMDViY2ZlOWY0ZmUyMDAwYjYxMGMiLCJlbWFpbCI6InNob3B0aXBqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTMzMjIwOTcsImV4cCI6MTY5MzQ5NDg5N30.IrwuI6HeZVJ4QBy5uCj_7H2td3upy32DhfqRjFhL7tQ

### Refresh token
POST {{baseUrlDev}}/refresh-token
Content-Type: application/json
x-api-key: 9acea3ac6cc47503e813c124d8a5b8a7f6185ea714a8274df81dd0f735dd8cd67bb53c9eee65ecdb2cfa51d3f84c451a043c34f08da0668417717319aa4f1c46
x-client-id: 64ea05bcfe9f4fe2000b610c
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVhMDViY2ZlOWY0ZmUyMDAwYjYxMGMiLCJlbWFpbCI6InNob3B0aXBqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTMzMjIwOTcsImV4cCI6MTY5MzQ5NDg5N30.IrwuI6HeZVJ4QBy5uCj_7H2td3upy32DhfqRjFhL7tQ
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVhMDViY2ZlOWY0ZmUyMDAwYjYxMGMiLCJlbWFpbCI6InNob3B0aXBqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTMzMjIwOTcsImV4cCI6MTY5MzkyNjg5N30.CRGNnIsVMNsRMWf9XBq7Yp-Mmxty8MWndPhp60DaksY
