@baseUrlDev=http://localhost:3055/v1/api/product


### Create a new product
POST {{baseUrlDev}}
Content-Type: application/json
x-api-key: 9acea3ac6cc47503e813c124d8a5b8a7f6185ea714a8274df81dd0f735dd8cd67bb53c9eee65ecdb2cfa51d3f84c451a043c34f08da0668417717319aa4f1c46
x-client-id: 64df8ee8444a29f029912923
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGRmOGVlODQ0NGEyOWYwMjk5MTI5MjMiLCJlbWFpbCI6InNob3B0aXBqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTMwNTExMDQsImV4cCI6MTY5MzIyMzkwNH0.1AlNCcRIN9nYN9aomfYrRZ2XMeycfmBNJFdhkdyH9yI

{
    "productName": "New Jeans",
    "productThumb": "product_thumb",
    "productDescription": "Hight-quanlity denim jeans",
    "productPrice": 50,
    "productQuantity": 5,
    "productType": "Clothing",
    "productShop": "64df8ee8444a29f029912923",
    "productAttributes": {
        "brand": "levi s",
        "size": "L",
        "material": "Denim"
    }
}